format_version: v1.0
configName: lcdc_rgba8888_mxt_9x60_wvga
folderName: legato_wm_9x60_ek_tm5000
frameworkPath: C:\Users\c40450\harmony3
processor: SAM9X60
projectName: legato_wm_9x60_ek_tm5000
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAM9X6_DFP\1.7.85\atdf\SAM9X60.atdf
